export const locale = {
  localeDetection: true,
  availableLanguages: ["en", "Русский"],
  translations: {
    Русский: {
      labels: {
        Property: "Недвижимость",
        Developer: "Застройщик",
        Settings: "Настройки",
        User: "Пользователь",
        Sells: "Продажи",
        Booking: "Бронирование",
        Payment: "Платежи",
        File: "Купленные аналитика лота",
        Auction: "Купленные места аукционы",
        Contact: "Запросы на обратную связь по лоту",
        Cities: "Города",
        LotContactForm: "Запросы на добавление лота",
        Favorite: "Избранное",
        Country: "Страна",
      },
      properties: {
        SearchPageBannerImage: "Изображение на баннере страницы показать еще",
        propertyPageBannerImage: "Изображение на баннере страницы недвижимости",
        showMorePageBannerLink: "Ссылка на баннере страницы показать еще",
        SearchPageBannerLink: "Ссылка на баннере страницы показать еще",
        mainPageBannerLink: "Ссылка на баннере главной",
        propertyPageBannerLink: "Ссылка на баннере страницы недвижимости",
        SearchPageBannerTextTitle: "Заголовок на баннере страницы показать еще",
        SearchPageBannerTextSubtitle:
          "Подзаголовок на баннере страницы показать еще",
        country: "Страна",
        "properties.isCompleted.true": "Да",
        dealCapitalIncrease: "Увеличение капитала сделки",
        dealProfitability: "Доходность сделки",
        dealOverview: "Обзор сделки",
        "info.rentalRate": "Арендная ставка",
        "info.repairCost": "Стоимость ремонта",
        "info.priceOverTime": "Цена со временем",
        "info.liquidity": "Ликвидность",
        "info.roi": "ROI",
        "info.sale": "Продажа",
        "info.price": "Арендная ставка",
        "buyOptions.flipping": "Флиппинг",
        "buyOptions.rental": "Аренда",
        "buyOptions.resale": "Перепродажа",
        "map.near.title": "Заголовок",
        "map.near.distance": "Расстояние",
        "coords.lat": "Широта",
        "coords.lng": "Долгота",
        deal: "Сделка",
        caprital: "Капитал",
        increase: "Увеличение",
        capitalIncrease: "Увеличение капитала",
        onMainPage: "Отображать на главной странице",
        type: "Тип",
        isAnswerd: "Отвечено?",
        comment: "Комментарий",
        id: "ID",
        user: "Пользователь",
        image: "Изображение",
        totalOffers: "Всего предложений",
        filePrice: "Стоимость аналитики",
        mapNear: "Ближайшие объекты",
        createdAt: "Дата создания записи",
        mainPageBannerText: "Текст на баннере главной",
        mainPageBannerTextSubtitle: "Подзаголовок на баннере главной",
        propertyPageBannerText: "Текст на баннере страницы недвижимости",
        propertyPageBannerTextSubtitle:
          "Подзаголовок на баннере страницы недвижимости",
        showMorePageBannerText: "Текст на баннере страницы показать еще",
        showMorePageBannerTextSubtitle:
          "Подзаголовок на баннере страницы показать еще",
        mapNearTitle: "Заголовок",
        city: "Город",
        name: "Название",
        iin: "ИИН",
        phone: "Телефон",
        numberOfDocument: "Номер документа",
        property: "Недвижимость",
        file: "Файл",
        amount: "Сумма",
        success: "Успешно",
        payment: "Платеж",
        book: "Сумма для бронирования",
        isCompleted: "Объект достроен?",
        isBooked: "Забронировано?",
        isSold: "Продано?",
        rating: "Рейтинг",
        financialStability: "Финансовая устойчивость",
        mainPageImage: "Изображение на главной",
        mainPageTitle: "Заголовок на главной",
        mainPageSubtitle: "Подзаголовок на главной",
        title: "Название",
        images: "Изображения",
        area: "Дата",
        address: "Адрес",
        coords: "Координаты",
        saleType: "Тип продажи",
        timer: "Таймер",
        isTimer: "Таймер включен",
        propertyType: "Тип недвижимости",
        price: "Цена",
        developer: "Застройщик",
        buyOptions: "Опции покупки",
        info: "Информация",
        building: "Строительство",
        description: "Описание",
        roi: "ROI",
        liquidity: "Ликвидность",
        priceOverTime: "Цена со временем",
        repairCost: "Стоимость ремонта",
        sale: "Продажа",
      },

      actions: {
        new: "Создать",
        edit: "Редактировать",
        show: "Показать",
        delete: "Удалить",
        list: "Список",
        search: "Поиск",
        filter: "Фильтр",
        export: "Экспорт",
        bulkDelete: "Удалить все",
        deleteMany: "Удалить все",
      },

      buttons: {
        save: "Сохранить",
        addNewItem: "Добавить",
        filter: "Фильтр",
        applyChanges: "Применить",
        resetFilter: "Сбросить",
        confirmRemovalMany:
          "Вы уверены что хотите удалить все выбранные элементы?",
        confirmRemoval: "Вы уверены что хотите удалить этот элемент?",
        loginWelcome: "Добро пожаловать",
        logout: "Выйти",
      },

      messages: {
        successfullyBulkDeleted: "Элементы успешно удалены",
        successfullyDeleted: "Элемент успешно удален",
        successfullyUpdated: "Элемент успешно обновлен",
        thereWereValidationErrors: "Ошибка валидации",
        forbiddenError: "Доступ запрещен",
        anyForbiddenError: "Доступ запрещен",
        successfullyCreated: "Элемент успешно создан",
        bulkDeleteError: "Ошибка удаления",
        errorFetchingRecords: "Ошибка получения элементов",
        errorFetchingRecord: "Ошибка получения элемента",
        noRecordsSelected: "Элементы не выбраны",
        theseRecordsWillBeRemoved: "Элементы будут удалены",
        theseRecordsWillBeUpdated: "Элементы будут обновлены",
        pickSomeFirstToRemove: "Выберите элементы для удаления",
        pickSomeFirstToUpdate: "Выберите элементы для обновления",
        error404Resource: "Элемент не найден",
        error404Action: "Элемент не найден",
        error404Record: "Элемент не найден",
        seeConsoleForMore: "Подробности в консоли",
        noActionComponent: "Не указан компонент для действия",
        noRecordsInResource: "Элементы не найдены",
        confirmDelete: "Вы уверены что хотите удалить этот элемент?",
        loginWelcome: "Добро пожаловать",
        logout: "Выйти",
      },
    },
  },
};
