import React from "react";
import {
  hamburger,
  navUser,
  conditions,
  contact,
  login,
  favorite,
  favoriteFilled,
  language,
  dropDown,
  dropDownActive,
  property,
  propertyActive,
  salesStart,
  timer,
  auction,
  buisness,
  investDeals,
  facebook,
  instagram,
  youtube,
  chat,
  eyeVisible,
  eyeInvisible,
  emailImage,
  arrowRight,
  arrowLeft,
  arrowDown,
  searchIcon,
  info,
  building,
  user,
  headphones,
  speaker,
  ellipse,
  email,
  phone,
  edit,
  upload,
  close,
  checkmark,
  card,
  kaspi,
  telegramChat,
  noDocument,
  blackEdit,
  whiteEdit,
  empty,
  sort,
  download,
  bigCheckmark,
  infoBTN,
  telegram,
  twoChat,
  city,
  country,
  next,
  prev,
  inlot1,
  inlot2,
  inlot3,
  logoSVG,
  sortSecond,
  propertyActiveMobile,
} from "./RawData";

const icons = {
  infoBTN: infoBTN(),
  conditions: conditions(),
  contact: contact(),
  telegramChat: telegramChat(),
  favorite: favorite(),
  favoriteFilled: favoriteFilled(),
  kaspi: kaspi(),
  card: card(),
  language: language(),
  dropDown: dropDown(),
  dropDownActive: dropDownActive(),
  property: property(),
  propertyActive: propertyActive(),
  salesStart: salesStart(),
  timer: timer(),
  auction: auction(),
  buisness: buisness(),
  investDeals: investDeals(),
  facebook: facebook(),
  instagram: instagram(),
  youtube: youtube(),
  chat: chat(),
  eyeVisible: eyeVisible(),
  eyeInvisible: eyeInvisible(),
  emailImage: emailImage(),
  arrowRight: arrowRight(),
  arrowLeft: arrowLeft(),
  arrowDown: arrowDown(),
  searchIcon: searchIcon(),
  info: info(),
  building: building(),
  user: user(),
  headphones: headphones(),
  speaker: speaker(),
  ellipse: ellipse(),
  email: email(),
  phone: phone(),
  edit: edit(),
  upload: upload(),
  close: close(),
  checkmark: checkmark(),
  noDocument: noDocument(),
  blackEdit: blackEdit(),
  whiteEdit: whiteEdit(),
  empty: empty(),
  login: login(),
  sort: sort(),
  blueSort: sort("#4E77FB"),
  download: download(),
  bigCheckmark: bigCheckmark(),
  telegram: telegram(),
  twoChat: twoChat(),
  city: city(),
  country: country(),
  next: next(),
  prev: prev(),
  inlot1: inlot1(),
  inlot2: inlot2(),
  inlot3: inlot3(),
  hamburger: hamburger(),
  navUser: navUser(),
  logoSVG: logoSVG(),
  'sort-2': sortSecond(),
  propertyActiveMobile: propertyActiveMobile(),
};

export const Icon = ({ name }) => {
  return (
    <div
      style={{
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      {icons[name]}
    </div>
  );
};
